---
version: '3.8'

services:

  frontend:
    image: ghcr.io/plone/tagung-plone-de-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://testingtagung-plone-de_backend:8080/Plone
      RAZZLE_API_PATH: https://testingtagung.plone.de
    depends_on:
      - backend
    networks:
      - public
      - nw-testingtagungplonede
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # SERVICE
        - traefik.http.services.testingtagung_plonede-frontend.loadbalancer.server.port=3000
        # MIDDLEWARES
        ### ClassicUI Access Authentication
        - traefik.http.middlewares.testingtagung_plonede-frontend-auth.basicauth.users=plonetagung:$$2y$$05$$7jfejsi4CsRQpNBiorquEeuNZqDropPM4Wpox.lB0VsgIXjCk/ubC
        # HOSTS: Main
        - traefik.http.routers.testingtagung_plonede-frontend.rule=Host(`testingtagung.plone.de`)
        - traefik.http.routers.testingtagung_plonede-frontend.entrypoints=https
        - traefik.http.routers.testingtagung_plonede-frontend.tls=true
        - traefik.http.routers.testingtagung_plonede-frontend.tls.certresolver=le
        - traefik.http.routers.testingtagung_plonede-frontend.service=testingtagung_plonede-frontend
        - traefik.http.routers.testingtagung_plonede-frontend.middlewares=gzip,testingtagung_plonede-frontend-auth

  backend:
    image: ghcr.io/plone/tagung-plone-de-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-biBEDQfgjkWs}' port='${DB_PORT:-5432}'"
    networks:
      - public
      - nw-testingtagungplonede
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # SERVICE
        - traefik.http.services.testingtagung_plonede-backend.loadbalancer.server.port=8080
        # MIDDLEWARES
        ### ClassicUI Access Authentication
        - traefik.http.middlewares.testingtagung_plonede-backend-auth.basicauth.users=plonetagung:$$2y$$05$$7jfejsi4CsRQpNBiorquEeuNZqDropPM4Wpox.lB0VsgIXjCk/ubC
        ### Backend ++api++ VHM
        - "traefik.http.middlewares.testingtagung_plonede-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.testingtagung_plonede-vhm.replacepathregex.replacement=/VirtualHostBase/https/testingtagung.plone.de/Plone/++api++/VirtualHostRoot/$$1"
        ### Backend ClassicUI VHM
        - "traefik.http.middlewares.testingtagung_plonede-vhm-classicui.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.testingtagung_plonede-vhm-classicui.replacepathregex.replacement=/VirtualHostBase/https/testingtagung.plone.de/Plone/VirtualHostRoot/_vh_ClassicUI/$$1"
        # ROUTES
        ## API
        - traefik.http.routers.testingtagung_plonede-backend.rule=Host(`testingtagung.plone.de`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.testingtagung_plonede-backend.entrypoints=https
        - traefik.http.routers.testingtagung_plonede-backend.tls=true
        - traefik.http.routers.testingtagung_plonede-backend.service=testingtagung_plonede-backend
        - traefik.http.routers.testingtagung_plonede-backend.middlewares=gzip,testingtagung_plonede-vhm
        ### /ClassicUI - protected with basic auth (prevent SEOs from crawling it)
        - traefik.http.routers.testingtagung_plonede-classicui.rule=Host(`testingtagung.plone.de`) && (PathPrefix(`/ClassicUI`))
        - traefik.http.routers.testingtagung_plonede-classicui.entrypoints=https
        - traefik.http.routers.testingtagung_plonede-classicui.tls=true
        - traefik.http.routers.testingtagung_plonede-classicui.service=testingtagung_plonede-backend
        - traefik.http.routers.testingtagung_plonede-classicui.middlewares=gzip,testingtagung_plonede-backend-auth,testingtagung_plonede-vhm-classicui

networks:


networks:
  public:
    external: true
  nw-testingtagungplonede:
    internal: true
    driver: overlay
